;;; vertico-posframe-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vertico-posframe.el

(defvar vertico-posframe-mode nil
"Non-nil if Vertico-Posframe mode is enabled.
See the `vertico-posframe-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `vertico-posframe-mode'.")
(custom-autoload 'vertico-posframe-mode "vertico-posframe" nil)
(autoload 'vertico-posframe-mode "vertico-posframe"
"Display Vertico in posframe instead of the minibuffer.

This is a global minor mode.  If called interactively, toggle the
`Vertico-Posframe mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='vertico-posframe-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'vertico-posframe-cleanup "vertico-posframe"
"Remove frames and buffers used for vertico-posframe." t)
(register-definition-prefixes "vertico-posframe" '("vertico-posframe-"))

;;; End of scraped data

(provide 'vertico-posframe-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vertico-posframe-autoloads.el ends here
