;;; flyspell-correct-ivy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flyspell-correct-ivy.el

(autoload 'flyspell-correct-ivy "flyspell-correct-ivy" "\
Run `ivy-read' for the given CANDIDATES.

List of CANDIDATES is given by flyspell for the WORD.

Return result according to `flyspell-correct-interface'
specification.

(fn CANDIDATES WORD)")
(register-definition-prefixes "flyspell-correct-ivy" '("flyspell-correct-ivy-"))

;;; End of scraped data

(provide 'flyspell-correct-ivy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flyspell-correct-ivy-autoloads.el ends here
