;;; tokyo-night-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tokyo-night.el

(autoload 'tokyo-night-with-colors "tokyo-night" "\
Bind all palette colors for the current Tokyo theme and evaluate BODY.
Inside BODY, each palette color is available as a local variable,
e.g. `tokyo-blue', `tokyo-bg', etc.

Example:
  (tokyo-night-with-colors
    (set-face-attribute \\='some-face nil :foreground tokyo-blue))

(fn &rest BODY)" nil t)
(function-put 'tokyo-night-with-colors 'lisp-indent-function 0)
(autoload 'tokyo-night-reload "tokyo-night" "\
Reload the current Tokyo theme.
Useful after changing `tokyo-night-override-colors-alist' or
`tokyo-night-scale-headings' without having to call `load-theme'
manually." t)
(autoload 'tokyo-night-select "tokyo-night" "\
Select and load a Tokyo theme variant interactively." t)
(register-definition-prefixes "tokyo-night" '("tokyo-night-"))


;;; Generated autoloads from tokyo-night-day-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "tokyo-night-day-theme" '("tokyo-night-day"))


;;; Generated autoloads from tokyo-night-moon-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "tokyo-night-moon-theme" '("tokyo-night-moon"))


;;; Generated autoloads from tokyo-night-storm-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "tokyo-night-storm-theme" '("tokyo-night-storm"))


;;; Generated autoloads from tokyo-night-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "tokyo-night-theme" '("tokyo-night"))

;;; End of scraped data

(provide 'tokyo-night-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tokyo-night-autoloads.el ends here
