;;; 2048-game-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from 2048-game.el

(autoload '2048-game "2048-game" "\
Start playing 2048." t)
(register-definition-prefixes "2048-game" '("*2048-" "2048-" "in-bounds"))

;;; End of scraped data

(provide '2048-game-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; 2048-game-autoloads.el ends here
