;;; flymake-ruby-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-ruby.el

(autoload 'flymake-ruby-load "flymake-ruby" "\
Configure flymake mode to check the current buffer's ruby syntax." t)
(register-definition-prefixes "flymake-ruby" '("flymake-ruby-"))

;;; End of scraped data

(provide 'flymake-ruby-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-ruby-autoloads.el ends here
