;;; yankpad-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from yankpad.el

(autoload 'yankpad-set-category "yankpad" "\
Change the yankpad category." t)
(autoload 'yankpad-insert "yankpad" "\
Insert an entry from the yankpad.
Uses `yankpad-category', and prompts for it if it isn't set." t)
(autoload 'yankpad-capture-snippet "yankpad" "\
`org-capture' a snippet to current `yankpad-category' (prompts if not set)." t)
(autoload 'yankpad-expand "yankpad" "\
Replace symbol at point with a snippet.
Only works if the symbol is found in the first matching group of
`yankpad-expand-keyword-regex'.

This function can be added to `hippie-expand-try-functions-list'.

(fn &optional FIRST)" t)
(autoload 'yankpad-edit "yankpad" "\
Open the yankpad file for editing." t)
(autoload 'yankpad-map "yankpad" "\
Create and execute a keymap out of the last tags of snippets in `yankpad-category'." t)
(autoload 'company-yankpad "yankpad" "\
Company backend for yankpad.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "yankpad" '("company-yankpad--name-or-key" "yankpad-"))

;;; End of scraped data

(provide 'yankpad-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yankpad-autoloads.el ends here
