;;; gcode-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gcode-mode.el

(add-to-list 'auto-mode-alist '("\\.gco\\(?:de\\)?\\'" . gcode-mode))
(autoload 'gcode-mode "gcode-mode" "\
Major mode for G-Code instructions.

(fn)" t)
(register-definition-prefixes "gcode-mode" '("gcode-mode--"))


;;; Generated autoloads from gcode-mode-doc.el

(register-definition-prefixes "gcode-mode-doc" '("gcode-mode--doc-entries"))

;;; End of scraped data

(provide 'gcode-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gcode-mode-autoloads.el ends here
