;;; consult-ls-git-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-ls-git.el

(autoload 'consult-ls-git "consult-ls-git"
"Create a multi view for current git repository." t)
(autoload 'consult-ls-git-ls-files "consult-ls-git"
"Select a tracked file from a git repository." t)
(autoload 'consult-ls-git-ls-files-other-window "consult-ls-git"
"Select a tracked file from a git repository and open it in another window." t)
(autoload 'consult-ls-git-ls-status "consult-ls-git"
"Select a file from a git repository considered to be modified or untracked.

Untracked files are only included if `consult-ls-git-show-untracked-files' is t." t)
(autoload 'consult-ls-git-ls-status-other-window "consult-ls-git"
"Open a modified/untracked file from a git repository in another window.

Untracked files are only included if
`consult-ls-git-show-untracked-files' is t." t)
(autoload 'consult-ls-git-ls-stash "consult-ls-git"
"Select a stash from a git repository and apply, pop or drop it." t)
(autoload 'consult-ls-git-ls-ignored "consult-ls-git"
"Select an ignored file from a git repository." t)
(autoload 'consult-ls-git-ls-ignored-other-window "consult-ls-git"
"Select an ignored file from a git repository and open it in another window." t)
(register-definition-prefixes "consult-ls-git" '("consult-ls-git-"))

;;; End of scraped data

(provide 'consult-ls-git-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-ls-git-autoloads.el ends here
